kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  generateName: contoso-devops-pipeline-run-
spec:
  pipelineRef:
    name: contoso-devops-pipeline
  params:
    - name: "git-url"
      value: "https://github.com/pittar-sandbox/dotnet-contoso-app.git"
    - name: "git-revision"
      value: "main"
    - name: "app-name"
      value: "contoso"
    - name: "gitops-url"
      value: "https://github.com/pittar-sandbox/dotnet-contoso-gitops-developers.git"
    - name: "gitops-revision"
      value: "main"
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: build-workspace
    - name: gitops-source
      persistentVolumeClaim:
        claimName: gitops-workspace
